version: 2

updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # Auth
  - package-ecosystem: "npm"
    directory: "/backend/auth"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # Booking
  - package-ecosystem: "npm"
    directory: "/backend/booking-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # Chat
  - package-ecosystem: "npm"
    directory: "/backend/chat-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # Admin
  - package-ecosystem: "npm"
    directory: "/backend/admin-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # Search
  - package-ecosystem: "npm"
    directory: "/backend/search-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"

  # Dockerfiles
  - package-ecosystem: "docker"
    directory: "/backend/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend/booking-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend/chat-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend/admin-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend/search-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
