events {}

http {
  # app.example.com
  # app.localhost
  # app.mydomain.net
  server {
    listen 80;
    server_name ~^app\..+$;

    location / {
      proxy_pass http://dashboard:4173;
    }
  }

  # everything else
  server {
    listen 80 default_server;
    server_name _;

    location / {
      proxy_pass http://landing:3000;
    }
  }
}
