import { body } from "express-validator";

export const profileValidation = [
	body("full_name").optional().isString().trim(),
	body("photo_url").optional().isURL(),
	body("date_of_birth").optional().isISO8601(),
	body("gender").optional().isIn(["male", "female", "other"]),
	body("blood_type").optional().isString(),
	body("has_diabetes").optional().isBoolean(),
	body("has_hypertension").optional().isBoolean(),
	body("has_heart_disease").optional().isBoolean(),
	body("has_asthma").optional().isBoolean(),
	body("has_kidney_disease").optional().isBoolean(),
	body("is_pregnant").optional().isBoolean(),
	body("is_smoker").optional().isBoolean(),
	body("has_previous_surgeries").optional().isBoolean(),
	body("allergies").optional().isString(),
	body("current_medications").optional().isString(),
	body("family_history").optional().isString(),
	body("other_conditions").optional().isString(),
	body("emergency_contact").optional().isObject(),
	body("latitude").optional().isFloat(),
	body("longitude").optional().isFloat(),
	// Clinic/Pharmacy specific
	body("clinic_name").optional().isString(),
	body("pharmacy_name").optional().isString(),
	body("city").optional().isString(),
	body("address").optional().isString(),
	body("google_maps_url").optional().isURL(),
	body("phone_numbers").optional().isArray(),
	body("description").optional().isString(),
	// Doctor specific
	body("specialty").optional().isString(),
	body("phone_number").optional().isString(),
	body("is_active").optional().isBoolean(),
];
