apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../mlflow

replicas:
  - name: cbc-api
    count: 1

configMapGenerator:
  - name: cbc-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG

patches:
  - target:
      kind: Deployment
      name: cbc-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: omaraldujawy/cbc-api:dev
  - target:
      kind: Ingress
      name: cbc-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: cbc-api.dev.local
